name: "Home Task Scheduler"
description: "Home Assistant Addon to schedule Home Tasks"
version: "1.0.2"
slug: "task_scheduler"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000